Voorstel toevoeging 'alternatieve' om breaking change te voorkomen, issue #198
Geonovum/MIM-Werkomgeving pull request #226
Opened 2022-01-23 12:16 UTC by architolk

2022-01-23 12:17 UTC, architolk commented
Gelinkt aan #198

2022-01-24 06:38 UTC, pmaria commented
In mijn optiek leidt de aanscherping van Lennart in #210 automatisch tot een breaking change in de Linked Data transformatie.
Op zich prima om het voor deze versie zo te laten, maar dan moeten we dit in de Y versie wel goed aanpakken.

2022-01-24 08:39 UTC, lennartvanbergen-kadaster commented
Dit voorstel is juist zo opgeschreven om een breaking change te (kunnen) voorkomen. Je moet er wel iets voor doen in de mapping: 

ALS alias niet gevuld, DAN staat de normale schrijfwijze in de naam van het modelelement 
ALS alias wel is gevuld, DAN staat de normale schrijfwijze in de alias, en de technische schrijfwijze in de naam van het modelelement 

Dit is altijd zo geweest, dus het is mijn inziens geen breaking change. Alsmede, je kan met voorgaand algoritme(tje) voorkomen dat het een breaking change wordt. Tot slot, als er een bug in de LD kant zit, een bug oplossen mag een breaking change zijn.

2022-01-24 08:47 UTC, lennartvanbergen-kadaster commented
De definitie aanpassen kan als volgt: 
Alias; de schrijfwijze van de naam van het modelelement in natuurlijke taal. 
Toelichting; de alias is alleen gevuld wanneer de naam van het model element zelf niet in natuurlijke taal is beschreven, maar bijvoorbeeld een camel case of snake case schrijfwijze hanteert.

2022-01-24 08:52 UTC, lennartvanbergen-kadaster requested changes
De definitie aanpassen kan als volgt: 
Alias; de schrijfwijze van de naam van het modelelement in natuurlijke taal. 
Toelichting; de alias is alleen gevuld wanneer de naam van het model element zelf niet in natuurlijke taal is beschreven, maar bijvoorbeeld een camel case of snake case schrijfwijze hanteert. 

Het woord alternatieve naam kan hier niet, omdat dan nog steeds niet duidelijk is welke van de twee de natuurlijke schrijfwijze is en welke de camel case of snake case. Als A een alternatief is van B, dan is B ook een alternatief van A, en dan weet je nog steeds niet of A de natuurlijke schrijfwijze bevat of B. Het gaat hier niet om alternatieve namen maar om alternatieve schrijfwijzen. Dit voorstel lijkt me daarom niet te matchen met de intentie van alias.

2022-01-24 12:16 UTC, architolk commented
Maar, euh... mim:naam is toch de "echte" naam? En dus is elke andere naam toch een "alternatieve naam"? Er zit geen bug in de LD kant, maar het voorstel zoals het nu wordt gedaan is onduidelijk. De huidige versie van MIM staat het toe om in mim:naam zowel een wat meer "technischere" naam op te nemen als ook de naam in natuurlijke taal. Dit is afhankelijk van welke keuze je maakt (die op dit moment dus niet formeel wordt afgedwongen).

2022-01-24 12:39 UTC, architolk commented
Wat mij betreft mag deze pull request vervallen: met het voorstel van Pano (zie #198), is duidelijk hoe we er mee omgaan aan de LD kant, namelijk: niet transformeren, dan maakt het niet meer uit wat mim:alias betekent, en is er ook geen breaking change meer.

2022-01-26 08:27 UTC, lennartvanbergen-kadaster commented
Vanwege laatste opm @architolk dit pull request gesloten.

2022-01-26 08:27 UTC, closed without merging