148 relatieklassen modelleren als objecttype
Geonovum/MIM-Werkomgeving pull request #328
Opened 2023-08-16 15:49 UTC by lennartvanbergen

verwerking van #148 

Korte tekst voor versie log van issue van 1.1.1 naar 1.2: 
Er zijn uitzonderlijke situaties waarin een relatieklasse beter gemodelleerd kan worden als een objecttype. Er is beschreven wanneer dit het geval is.

2023-08-18 12:23 UTC, pmaria requested changes

2023-08-18 12:23 UTC, pmaria commented on AfsprakenRegels.md
> +voor al deze relaties gelijk. Om deze reden wordt de relatieklasse 'overgegaan in' gemodelleerd als een objecttype.
Volgens mij halen we hier twee modelleerperspectieven door elkaar.

Je kunt prima meerdere instanties van een relatieklasse hebben, ook als deze dezelfde kenmerk, waarde combinaties hebben over alle gelijksoortige relaties in een specifiek gegevensobject. Ook als de gegevens van de relatie feitelijk gaan over hetzelfde ding vanuit een ander perspectief, bijvoorbeeld dezelfde splitsing.

Echter, wanneer je een splitsing als een aanwijsbaar ding wilt beschouwen in je UoD, zodat je gemakkelijk kunt opvragen welke objecten betrokken waren bij de splitsing, dan kun je dit als volwaardig Objecttype modelleren. 

(Dit zou ik echter niet modelleren met een 1 inkomende en 1 uitgaande relatie. Maar eerder met 1 uitgaande relatie naar het object wat gesplitst wordt, en met 1 of meerdere relaties naar de nieuwe afgseplitste objecten, maar over de richting kun je discussiëren.)

Daarmee verlies je wel het relatiegegeven "overgegaanIn" tussen de objecten.

Echter, het is ook mogelijk om een combinatie van een relatie, geobjectiveerd als Objecttype en dezelfde relatie als Relatiesoort of zelfs Relatieklasse, op te nemen in hetzelfde informatiemodel. Bijvoorbeeld een objecttype Splitsing èn een relatiesoort "overgegaanIn" tussen objecttyppen van het type "Perceel" (, wel of niet met afleidingsregels).
Het is maar afhankelijk van welke informatiebehoefte je in welke gevallen wilt kunnen bedienen.

Al met al komt het volgens mij neer op een modelleerkeuze afhankelijk van de informatiebehoefte.
Het beschrijven van dergelijke overwegingen hoort volgens mij dan ook meer thuis in een bijlage of in een primer.

2023-08-18 12:23 UTC, pmaria commented on AfsprakenRegels.md
> +beschreven wordt wat er moet gebeuren wanneer één van de SUBJECTen niet meer bestaat.
Hier geldt wat mij betreft hetzelfde als hierboven.

2023-08-18 12:23 UTC, pmaria commented on AfsprakenRegels.md
> +- de gegevens over de relatie bestaan alleen zolang de relatie tussen beide objecten bestaat en zolang elk van beide objecten zelf (nog) bestaan. Dit is echter niet meer te zien aan de metaklasse, om
> [...] en zolang elk van beide objecten zelf (nog) bestaan.

Ik denk niet dat het nodig is om het te hebben over het bestaan van de objecten. Het is voldoende om het te hebben over of de relatie nog bestaat, gezien de relatie het onderwerp is van de gegevens van de instantie van de bijbehorende relatieklasse.

> Dit is echter niet meer te zien aan de metaklasse, omdat dit «Objecttype» is geworden en niet meer «Relatieklasse» is. Geef daarom in de toelichting van het objecttype aan dat elk object van dit objecttype bestaansafhankelijk is van de beide objecttypen die verbonden zijn door deze geobjectiveerde relatie.

Ik snap niet echt wanneer dit optreedt. Behalve misschien in een vrij technische situatie in een database of zo. Maar hebben we het daarover?

2023-08-18 12:23 UTC, pmaria commented on AfsprakenRegels.md
> +- normaal gesproken bij relaties tussen objecten wordt de relatie op instantie niveau geïdentificeerd door de identificaties van beide betrokken objecten. Er zijn geen aparte regels voor de opbouw va
> normaal gesproken bij relaties tussen objecten wordt de relatie op instantie niveau geïdentificeerd door de identificaties van beide betrokken objecten.

En de kenmerkreferentie! Relatie(gegevens) wordt net als alle andere gegevens altijd geidentificeerd door de combinatie van het onderwerp, de kenmerkreferentie en de waarde,

> Er zijn geen aparte regels voor de opbouw van de identificatie van een relatieklasse (en ook niet voor geobjectiveerde relatieklassen die als objecttypen zijn gemodelleerd). Anders gezegd, een regel zoals dat de identificatie van een relatieklasse (of geobjectiveerde relatieklassen die als objecttypen zijn gemodelleerd) is opgebouwd uit de samenstelling van de identificatie van bron en doel objecten is niet aanwezig in de MIM specificatie. Evenzo bestaat er in MIM geen regel of best practise dat er een nieuwe betekenisloze identificatie toegekend moet worden. Het is aan de modelleur om hierin eigen afwegingen te maken.

Volgens mij is de identificatie van een geïnstantieerde relatieklasse precies hetzelfde als die van een relatie. Een relatieklasse is namelijk semantisch gelijk aan een relatiesoort.

Maar het zou goed zijn om te beschrijven wat we vinden dat die regel is.

2023-08-18 12:23 UTC, pmaria commented on AfsprakenRegels.md
> +
Waarom noemen we dit? Is hier een specifieke vraag naar? Anders zou ik het weglaten.

2023-10-12 14:14 UTC, Gtrouborst commented
@PalmJanssen: wil jij hier nog naar kijken of heb jij dat al gedaan?

2023-10-12 14:23 UTC, Gtrouborst commented
Merge conflicts met master opgelost

2023-10-13 04:05 UTC, pmaria commented
Ik heb dit een paar weken geleden met @lennartvanbergen besproken. De conclusie is dat we de aanpassing zouden versimpelen.  @lennartvanbergen ik was in de veronderstelling dat jij dat zou verwerken. Klopt dat?

2023-10-13 04:14 UTC, pmaria commented
zie ook https://github.com/Geonovum/MIM-Werkomgeving/issues/148#issuecomment-1721172986

2023-10-13 13:56 UTC, merged