definitie en toelichting codelijst aangepast
Geonovum/MIM-Werkomgeving pull request #341
Opened 2023-09-13 10:24 UTC by PalmJanssen

Naar aanleiding van issue 253 is er nog een tweede aanpassing gedaan in branche 253b. Definitie en toelichting van codelijst aangepast aan nieuwe metagegevens die we nu wel opnemen.

2023-09-13 10:44 UTC, pmaria requested changes
Er zijn in ieder geval nog een aantal issues gerelateerd hieraan:

* Deze wijzigingen moeten nog doorgevoerd worden in het LD stuk. Ik stel voor om dat mee te nemen in dit PR.
* metagegeven `Waarde-item` wordt [hier](https://github.com/Geonovum/MIM-Werkomgeving/blob/acb19139f00a182c92ef75fa6d2da69e558edf2e/MetamodelUML.md?plain=1#L608) `Waarde item` genoemd. Dit rechttrekken.
* metagegeven `Datatype` leidt tot een naamconflict met het bestaande modelelement `Datatype`. Dit is niet handig. Hier moeten we een andere naam voor verzinnen. 
* Het is mij nog niet helemaal duidelijk hoe een waarde uit een waardelijst een datatype kan hebben. Een waarde is al een datatype, volgens het metamodel. Een enumeratie heeft bijvoorbeeld ook geen datatype. Hoe werkt dit precies?
* Kan een datatype ook een objecttype zijn? Ofwel kun je hiermee een relatie uitdrukken?

2023-09-19 14:26 UTC, PalmJanssen commented
> * Deze wijzigingen moeten nog doorgevoerd worden in het LD stuk. Ik stel voor om dat mee te nemen in dit PR.
_OK maar wie gaat dat doen_
> * metagegeven `Waarde-item` wordt [hier](https://github.com/Geonovum/MIM-Werkomgeving/blob/acb19139f00a182c92ef75fa6d2da69e558edf2e/MetamodelUML.md?plain=1#L608) `Waarde item` genoemd. Dit rechttrekken.
_Is gebeurd. Nu overal Waarde-item_
> * metagegeven `Datatype` leidt tot een naamconflict met het bestaande modelelement `Datatype`. Dit is niet handig. Hier moeten we een andere naam voor verzinnen.
_Dit zie ik nergens terugkomen. Waar zit dat?_
> * Het is mij nog niet helemaal duidelijk hoe een waarde uit een waardelijst een datatype kan hebben. Een waarde is al een datatype, volgens het metamodel. Een enumeratie heeft bijvoorbeeld ook geen datatype. Hoe werkt dit precies?
_Ja dat dacht ik dat we ook bij enumeratiewaarde hadden toegevoegd op jouw verzoek. Je argument was dat het datatype betekenis toevoegde aan een waarde. Bij voorbeeld 747 als integer is iets anders dan 747 als CharacterString. Vind ik wel wat voor te zeggen, maar ik zie het nergens terugkomen in andere issues. Wat mij betrft kan het dan ook hier weg. Anders ook bij enumeratiewaarde toevoegen. Op zich kan dat in EA maar ik zie in het UML metamodel niet die mogelijkheid. Dus mijn advies geen datatype voor een waarde in een codelijst_
> * Kan een datatype ook een objecttype zijn? Ofwel kun je hiermee een relatie uitdrukken?
_Nee. Een datatype is geen ding, het heeft geen identiteit. Is dat wat je bedoelt?_

2023-09-20 11:49 UTC, pmaria commented
> > * Deze wijzigingen moeten nog doorgevoerd worden in het LD stuk. Ik stel voor om dat mee te nemen in dit PR.
> 
> _OK maar wie gaat dat doen_

Ik wil dat wel doen, maar dat gaat mij waarschijnlijk pas volgende week of de week daarna lukken.

> > * metagegeven `Datatype` leidt tot een naamconflict met het bestaande modelelement `Datatype`. Dit is niet handig. Hier moeten we een andere naam voor verzinnen.
> 
> _Dit zie ik nergens terugkomen. Waar zit dat?_

Zie https://geonovum.github.io/MIM-Werkomgeving/#respec-offender-this-is-defined-more-than-once-in-the-document
 
> > * Het is mij nog niet helemaal duidelijk hoe een waarde uit een waardelijst een datatype kan hebben. Een waarde is al een datatype, volgens het metamodel. Een enumeratie heeft bijvoorbeeld ook geen datatype. Hoe werkt dit precies?
> 
> _Ja dat dacht ik dat we ook bij enumeratiewaarde hadden toegevoegd op jouw verzoek. Je argument was dat het datatype betekenis toevoegde aan een waarde. Bij voorbeeld 747 als integer is iets anders dan 747 als CharacterString. Vind ik wel wat voor te zeggen, maar ik zie het nergens terugkomen in andere issues. Wat mij betrft kan het dan ook hier weg. Anders ook bij enumeratiewaarde toevoegen. Op zich kan dat in EA maar ik zie in het UML metamodel niet die mogelijkheid. Dus mijn advies geen datatype voor een waarde in een codelijst_

Ha, daar heb ik geen actieve herinnering aan 😅 . Volgens mij mist er scherpte in het definiëren wat een waardelijst en de items daarin precies representeren op dit moment.

> > * Kan een datatype ook een objecttype zijn? Ofwel kun je hiermee een relatie uitdrukken?
> 
> _Nee. Een datatype is geen ding, het heeft geen identiteit. Is dat wat je bedoelt?_

De vraag achter de vraag is meer. Als je toch een datatype kunt specificeren voor een item in een waardelijst dan ben je blijkbaar attribuutsoorten aan het definiëren (?!). Waarom zouden het dan niet mogelijk kunnen zijn om relatiesoorten te definieren waarvan de target een waardelijstitem is, door het specificeren van objecttype als type. 
Maar de fundamentelere vraag die eerst beantwoord moet worden is denk ik: wat representeren die waardes nu? Naar mijn idee zijn dat meestal geen waardes van attribuutsoorten.

2023-10-10 14:44 UTC, Gtrouborst approved these changes

2023-10-11 13:21 UTC, merged

2023-10-13 03:33 UTC, pmaria commented
@Gtrouborst Deze is gemerged zonder dat er iets is gedaan aan een aantal delen van mijn review. Dit moet mijn inziens nog gebeuren