195 tekstvoorstel opgenomen
Geonovum/MIM-Werkomgeving pull request #343
Opened 2023-09-20 12:39 UTC by PalmJanssen

graag review

2023-09-21 14:29 UTC, pmaria requested changes
Algemeen: ik ben niet overtuigd van deze uitbreiding van MIM. Wat mij betreft introduceert het onnodige complexiteit. Volgens mij kun je hetgeen hiermee bereikt geprobeerd te worden al bereiken met de huidige uitdrukkingskracht van MIM, en zouden we hele goede argumenten moeten hebben om dit te introduceren. Die argumenten mis ik. Ik denk dat we dit issue nog eens dieper moeten bespreken en uitwerken voordat we dit opnemen in de standaard.

2023-09-22 10:36 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +Een static overervingsrelatie of kortweg een static relatie wordt bij UML toegepast op een generalisatie. De aanleiding is meestal om multiple inheritance issues op te lossen in talen/specificaties d
> Static relatie zou ik weglaten

Je bedoelt als verkorting van 'static overervingsrelatie'?

2023-09-22 10:38 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +Een static overervingsrelatie of kortweg een static relatie wordt bij UML toegepast op een generalisatie. De aanleiding is meestal om multiple inheritance issues op te lossen in talen/specificaties d
Zou de term issues kunnen weglaten en duidelijk zeggen dat multiple inheritance in niet ondersteund wordt in sommige implementatie talen

2023-09-22 10:43 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +Een static overervingsrelatie of kortweg een static relatie wordt bij UML toegepast op een generalisatie. De aanleiding is meestal om multiple inheritance issues op te lossen in talen/specificaties d
Jawel. Maar we moeten dit ook weer niet te groot gaan maken. Iets definieren wat niet implementeerbaar is heeft geen of niet veel zin. Dat is jammer maar ook een realiteit. De static relatie is een constructie die daaraan tegenmoet komt. Je leest en definieert het semantisch correct en past het vervolgens middels een conventie aangepast toe in een implementatie taal (die nog niet zover is).

2023-09-22 10:45 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +Een static overervingsrelatie of kortweg een static relatie wordt bij UML toegepast op een generalisatie. De aanleiding is meestal om multiple inheritance issues op te lossen in talen/specificaties d
De term kenmerksoort komt in MIM niet voor. Ik denk dat iedereen weet wat hier wordt bedoeld.

2023-09-22 10:47 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +- In het conceptuele model wordt een van de twee overervingsrelaties van `Static` voorzien. Dit geeft aan welke qua classificatie wel semantisch gezien blijft gelden maar op in het logische model doo
Ik zou dit ook niet doen, maar begrijp de behoefte wel. Je geeft als het ware aan dat hier iets in het logische model gaat veranderen.

2023-09-22 10:56 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +- In het conceptuele model staan beide overervingsrelaties en in het logische wordt bij een relatie door de opsteller van dat model het `Static` element toegevoegd, om aan te geven dat bij het maken
Het zijn inderdaad twee verschillende use cases. Daar kan een gebruiker zenuwachtig van worden, maar je moet blijven nadenken. Opzich heeft het static op beide niveaus geen semantische betekenis maar alleen een betekenis voor de implementatie.

2023-09-22 10:59 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +- In het conceptuele model staan beide overervingsrelaties en in het logische wordt bij een relatie door de opsteller van dat model het `Static` element toegevoegd, om aan te geven dat bij het maken
Hebben we het al over gehad. Ik heb liever een constructie als deze dan dat ik een apart semantisch model niveau moet introduceren. Het blijft zo dat sommige het gaan gebruiken en anderen niet. Het is daarnaast een constructie die al een jaar of 15 nationaal ook internationaal wordt gebruikt. Zo vreemd is het dan niet dat men dit dan ook in MIM wil opnemen.

2023-09-22 11:00 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +*Toepassing:* Attribuutsoort
ja hier loop iets door elkaar.

2023-09-22 11:00 UTC, PalmJanssen commented on MetamodelUML.md
> +
idem

2023-09-22 11:03 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +Een static overervingsrelatie of kortweg een static relatie wordt bij UML toegepast op een generalisatie. De aanleiding is meestal om multiple inheritance issues op te lossen in talen/specificaties d
ZIt wat in. Ik kan het als voorbeeld noemen.

2023-09-22 11:06 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +Een static overervingsrelatie of kortweg een static relatie wordt bij UML toegepast op een generalisatie. De aanleiding is meestal om multiple inheritance issues op te lossen in talen/specificaties d
Ga tekst hier op aanpassen. Inderdaad mag multiple inheritance op niveau 3 ook. Maar je kan er voor kiezen om dat niet te doen omdat sommige implementatietalen dat niet ondersteunen.

2023-09-22 11:09 UTC, PalmJanssen commented on MetamodelAlgemeen.md
> +- In het conceptuele model wordt een van de twee overervingsrelaties van `Static` voorzien. Dit geeft aan welke qua classificatie wel semantisch gezien blijft gelden maar op in het logische model doo
Ik ook niet. Maar je geeft alvast aan dat als er een logisch model komt waar je de multiple inheritance uit wilt halen waar je dit er uit wilt halen. Je kan dan ook snel zien waar het conceptuele model verschilt van het logische.

2023-09-27 10:40 UTC, closed without merging

2023-09-27 10:40 UTC, PalmJanssen commented
closed because of major changes from static to mixin