definitie object aangepast
Geonovum/MIM-Werkomgeving pull request #491
Opened 2024-02-29 15:38 UTC by PalmJanssen

2024-02-29 16:39 UTC, pmaria commented on MetamodelAlgemeen.md
> +  <dfn data-lt="objecten">Object</dfn>Een fenomeen in de werkelijkheid.
Zouden we dan niet beter kunnen zeggen : "in **een** werkelijkheid"?

2024-03-22 12:38 UTC, lennartvanbergen requested changes
Dit is echt slechter dan wat we hadden. 

zoals ernaar gekeken wordt vanuit een bepaald domein is een cruciaal onderdeel van de definitie. 

fenomeen zegt mij nog veel minder dan de oude definitie

hier wil ik echt voor gaan liggen ... 

liever geen wijziging dan deze.

2024-03-22 12:51 UTC, lennartvanbergen commented
Hier nog wel iets van werk in. Wat er nu staat vind ik (blocking) niet een verbetering. Graag terugdraaien of verbeteren.

2024-03-26 09:27 UTC, PalmJanssen commented
suggestie:

@pmaria @lennartvanbergen 

Object: Een fenomeen in de werkelijkheid zoals daarnaar wordt gekeken vanuit een bepaald domein.

2024-03-26 09:37 UTC, pmaria commented
> suggestie:
> 
> @pmaria @lennartvanbergen
> 
> Object: Een fenomeen in de werkelijkheid zoals daarnaar wordt gekeken vanuit een bepaald domein.


Tja, zelf zou ik het heel simpel houden.

> Een object is een onderwerp van gegevens.

Dit maakt dat we ons niet te veel beperken. Zo kan straks een gegeven zelf ook een object zijn.

In de toelichting kun je dan verder uitwijden met voorbeelden van wat een object zou kunnen zijn.

2024-03-28 16:21 UTC, architolk commented
We proberen wel de meest filosofische verbeteringen in de laatste loodjes te leggen :-D

We hadden:
"Een ding, een tastbaar iets, in de werkelijkheid, zoals daarnaar gekeken wordt vanuit een bepaald domein."

Een duidelijk beperking is hier dat het een "tastbaar iets" moet zijn, dat is sowieso niet houdbaar.

Beter zou dan al zijn:

"Een ding in de werkelijkheid, zoals daarnaar gekeken wordt vanuit een bepaald domein."

Je kunt vinden dat fenomenen in het algemeen geen "dingen" zijn of dat personen geen "dingen" zijn, dus je kunt het uitbreiden in de zin van:

"Een persoon, gebeurtenis, plek of ding, ..."

..maar ook dan ben je niet compleet :-(

Bij de Politie hanteren we nu deze definitie:

"Een object is een identificeerbaar iets in het beschouwde domein"

Die vind ik best aardig (wij van WC-eend ;-), maar ik kan me ook prima vinden in de originele, mits daar "tastbaar iets" vanaf gaat, aangezien je anders heel veel zaken niet kunt benoemen (bv "Eigendom" in de BRK :-O)

Overigens zit in deze definitie iets dat in de originele niet zat, namelijk dat een object identificeerbaar moet zijn. Dat is denk ik wel randvoorwaardelijk, maar goed.... ik wil de filosofische discussie niet helemaal op hol brengen...

Over het punt van "de werkelijkheid" vs "een werkelijkheid" => Dat zou je wellicht in de toelichting kunnen stoppen. Als je immers al vanuit een bepaald domein kijkt of beschouwd, dan moet je ook nadenken over wat je "de" werkelijkheid vindt ("de" werkelijkheid bestaat niet volgens veel filosofen...)

2024-03-29 09:20 UTC, PalmJanssen commented
Ik heb de tekst aangepast in de richting van de politie. Ik vind die definitie wel praktisch en plastisch.
Graag jullie mening (approval)
@pmaria @lennartvanbergen @architolk

2024-03-29 09:56 UTC, pmaria requested changes

2024-03-29 09:56 UTC, pmaria commented on MetamodelAlgemeen.md
> +  <dfn data-lt="objecten">Object</dfn>Een object is een identificeerbaar iets in het beschouwde domein.
```suggestion
  <dfn data-lt="objecten">Object</dfn>Een object is een onderscheidbaar iets in het beschouwde domein.
```

Identificeerbaar vind ik erg lastig. Dit doet denken dat elk object en dus elk objecttype een identificeerbaar kenmerk moet hebben in een logisch gegevensmodel. Dat is niet zo. Er kunnen prima objecten zijn die we niet willen of kunnen identificeren.
Ik stel voor om identificeerbaar te vervangen met onderscheidbaar.

2024-04-02 06:33 UTC, lennartvanbergen approved these changes

2024-04-02 06:35 UTC, lennartvanbergen commented
Nja, tastbaar, er staat bij de toelichting: 

‘Tastbaar’ moet hierbij ruim geïnterpreteerd worden. Het gaat niet alleen om fysiek herkenbare objecten zoals auto’s, gebouwen en mensen, ook om zogenaamde virtuele objecten waarover binnen het domein door betrokkenen gecommuniceerd wordt zoals kadastrale percelen, (maatschappelijke) activiteiten en processen. Hoe een ‘tastbaar iets’ als een object beschouwd wordt, hangt af van het domein waarvoor dat ‘tastbaar iets’ relevant is. Zo wordt de gebouwde omgeving in het ene domein beschouwd als een verzameling gebouwen terwijl een ander domein daarin panden onderscheidt. Een object is voor een domein relevant als eigenschappen (kenmerken) daarvan van belang zijn voor het functioneren van dat domein. 

--
Het lijkt me wel nuttig om virtueel een plek te geven, immers, dat doet NEN3610 ook. 

Kan me wel vinden in de nieuwe tekst, maar ik snap niet zo goed waarom virtuele objecten eruit geschreven is.

2024-04-02 08:10 UTC, PalmJanssen commented
Virtuele objecten staan in de toelichting: en object is daarbij niet altijd fysiek het kunnen ook digitale, virtuele en conceptuele dingen zijn zoals administratieve grenzen, kadastrale percelen, (maatschappelijke) activiteiten en processen.

2024-04-02 08:18 UTC, merged