Wijziging van metadata element 'uri' naar 'modelelement identificatie'
Geonovum/MIM-Werkomgeving pull request #500
Opened 2024-03-07 15:40 UTC by ThiesMesdag

zie ook issue 480

2024-03-14 10:41 UTC, Bakkej requested changes
Aanvullend. Misschien is het een kwestie van voorkeur, maar waarom noemen we het metagegeven "model identificatie" niet gewoon "identificatie"? Er is immers ook geen metagegeven "modelelement naam" of "modelelement definitie".

2024-03-14 10:41 UTC, Bakkej commented on MetamodelAlgemeen.md
> +*Toelichting* De idenficatie van een modelelement kan bijvoorbeeld op de volgende twee manieren worden samengesteld, als **urn-URI**: `<urn:modelelement:imbaglv:objecten:Pand` of als **http-URI**: `<
idenficatie --> identificatie

modelelememt --> modelelement

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +Daarnaast geldt dat het in Linked Data gebruikelijk is om URI's over te nemen van andere (externe) vocabulaires c.q. modellen. Ook het MIM ondersteund dit, in de vorm van de mim metamodelklassen `mim
mim:modelelementidentificatie --> mim:modelelementIdentificatie

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +Indien sprake is van een view package, dan wordt de `mim:basisUri` en/of de expliciet ingevulde `mim:modelelementidentificatie` van deze view package alleen gebruikt voor de vocabulaire URI's (voorko
casing mim:modelelementidentificatie

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +De identificatie van een attribuutsoort is afgeleid van de `mim:modelelementidentificatie` van het attribuutsoort. Voor de propertyshape geldt dat deze ook nog afhankelijk is van de naam van het obje
casing modelelementidentificatie

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +De URI van de propertyshape wordt afgeleid van de naam van het modelelement dat de attribuutsoort "bezit" en de naam van de attribuutsoort. De URI van de `owl:DatatypeProperty` is gelijk aan de mim:m
casing modelelementidentificatie

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +De URI van de propertyshape wordt afgeleid van de naam van het modelelement dat de gegevensgroep "bezit" en de naam van de gegevensgroep. De URI van de `owl:ObjectProperty` is gelijk aan de mim:model
idem

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +De URI van de propertyshape wordt afgeleid van de naam van het modelelement dat de relatiesoort "bezit" en de naam van de relatiesoort. De URI van de `owl:ObjectProperty` is gelijk aan de mim:modelel
idem

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +De URI van de propertyshape wordt afgeleid van de naam van het modelelement dat de relatierol "bezit" en de naam van de relatierol. De URI van de `owl:ObjectProperty` is gelijk aan de mim:modelelemen
idem

2024-03-14 10:41 UTC, Bakkej commented on TransformatieRDF.md
> +| IRI | mim:modelelementidentificatie | De identificatie (URI) van het modelelement wordt in mim vastgelegd als eigenschap |
idem

2024-03-14 12:49 UTC, ThiesMesdag commented on MetamodelAlgemeen.md
> +*Toelichting* De idenficatie van een modelelement kan bijvoorbeeld op de volgende twee manieren worden samengesteld, als **urn-URI**: `<urn:modelelement:imbaglv:objecten:Pand` of als **http-URI**: `<
verbeterd

2024-03-19 15:54 UTC, PalmJanssen approved these changes
akkoord

2024-03-20 11:53 UTC, merged